metainfo:
  name: forTest
  description: Distribute configure
  date: 2023/12/28 21:00
  md5: xxx-xxx-zzz=zzz-ppp
  version: 0.1
  author: andy.hu

global:
  fileStore: "c:\\fileStore"
  log: ""

users:
  add:
    - name: it1
      password: "Password!"
      description: for testing1
      group: administrators
    - name: it2
      password: "Password!"
      description: for testing2
      group: administrators
    - name: it3
      password: "Password!"
      description: for testing3
      group: administrators
  delete:
    - name: it2
  rename:
    - name: it1
      newName: itadmin


files:
  - name: OpenSSH-Win64-v9.4.0.0.msi
    uri: "https://it2u.oss-cn-shenzhen.aliyuncs.com/winSoft/OpenSSH-Win64-v9.4.0.0.msi"
    setup: msiexec /i OpenSSH-Win64-v9.4.0.0.msi /quiet
  - name: npp.8.6.Installer.x64.exe
    uri: "https://it2u.oss-cn-shenzhen.aliyuncs.com/winSoft/npp.8.6.Installer.x64.exe"
    setup: npp.8.6.Installer.x64.exe /S
  - name: setup.exe
    uri: "https://dl.360safe.com/setup.exe"
    setup: setup.exe /S
  - name: duba_100_100.exe
    uri: https://cd001.www.duba.net/duba/install/packages/ever/duba_100_100.exe
    setup: duba_100_100.exe /S

registy:
  - terminal encoding:
    path: ""
    method: ""
    type: ""
    value: ""
  - powershell encoding:
    path: ""
    method: ""
    type: ""
    value: ""

tasks:
  - task1:
    name: "inventory"
    action: ""
    trigger: ""
    principal: ""
    settings: ""
  - task2:
    name: "health"
    action: ""
    trigger: ""
    principal: ""
    settings: ""
  - task3:
    name: "remedy"
    action: ""
    trigger: ""
    principal: ""
    settings: ""

services:
  - service1:
    name: "controller"
    binaryPathName: ""
    displayName: ""
    description: ""
    startupType: ""

scripts:
  - script1:
      name: consolidation
      type: security
      uri: "http://zzzz"
      action: "cmd"
  - script2:
      name: consolidation
      type: audio
      uri: "http://zzzzxx"
      action: "cmd"
